name: example
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  # sdk: '>=2.8.0 <3.0.0'
  sdk: ">=2.12.0-259.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
